name: CI
on: [push]
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 14, 16 ]
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Set up Node.js ${{ matrix.node }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: yarn

      - name: Lint
        run: yarn workspace @primer/gatsby-theme-doctocat lint

      - name: Test
        run: yarn workspace @primer/gatsby-theme-doctocat test
